name: Compile LaTeX to PDF

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
    
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Resume
        path: resume.pdf
        
    - name: Commit PDF to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.pdf
        git commit -m "Update resume.pdf" || echo "No changes to commit"
        git push
